Update autocomplete-component.md
ember-brasil/website pull request #58
Opened 2017-09-09 17:36 UTC by aureliosaraiva

2017-09-09 17:37 UTC, aureliosaraiva commented
10 words might be misspelled, please check them: ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit

2017-09-09 17:47 UTC, aureliosaraiva commented
11 words might be misspelled, please check them: disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit

2017-09-09 17:47 UTC, aureliosaraiva commented
11 words might be misspelled, please check them: disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit

2017-09-09 18:02 UTC, aureliosaraiva commented on source/guides/tutorial/autocomplete-component.md
> +#### Atualizando as declarações de componente
Preciso pensar em uma tradução melhor.

2017-09-09 18:02 UTC, aureliosaraiva commented
11 words might be misspelled, please check them: disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit

2017-09-09 18:15 UTC, aureliosaraiva commented on source/guides/tutorial/autocomplete-component.md
> -If the property changes, either by the user typing in the input field, or by assigning a new value to it in our program,
Achei meio estranho esse texto, não me pareceu dizer nada de útil.

2017-09-09 18:15 UTC, aureliosaraiva commented
12 words might be misspelled, please check them: compenent, disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit

2017-09-09 18:49 UTC, aureliosaraiva commented
15 words might be misspelled, please check them: compenent, conveção, coresponde, disponiveis, disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit

2017-09-09 21:44 UTC, aureliosaraiva commented
15 words might be misspelled, please check them: compenent, conveção, coresponde, disponiveis, disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit

2017-09-09 22:01 UTC, aureliosaraiva commented
17 words might be misspelled, please check them: compenent, conveção, coresponde, disponiveis, disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, init, keyEvent, keyup, keyUp, QUnit, testámos, toc

2017-09-09 22:48 UTC, aureliosaraiva commented
18 words might be misspelled, please check them: compenent, conveção, coresponde, disponiveis, disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, hbs, ímoveis, init, keyEvent, keyup, keyUp, QUnit, testámos, toc

2017-09-09 23:48 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +#### Atualizando as declarações de componente
`Marcações de Component` ?

2017-09-09 23:49 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> -If the property changes, either by the user typing in the input field, or by assigning a new value to it in our program,
Acho que talvez seja útil sim, explica como funciona a sincronia dos valores em um componente. Apesar de simples, dá uma visão do binding

2017-09-10 00:20 UTC, aureliosaraiva commented on source/guides/tutorial/autocomplete-component.md
> -If the property changes, either by the user typing in the input field, or by assigning a new value to it in our program,
Sim, o texto original traduzido é ruim, preciso pensar em um forma melhor de explicar isso em português.

2017-09-10 03:04 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> -If the property changes, either by the user typing in the input field, or by assigning a new value to it in our program,
Entendi. Podemos traduzir e inserir algumas melhorias que façam mais sentido. Não sei, talvez algo como: `Para manter o valor de uma propriedade atualizada, o Ember realiza o binding (link). Então, se uma propriedade trocar de valor, seja por uma ação do usuário ou seja por uma reatribuição via código, através do binding o Ember manterá o valor sincronizado com o que é apresentado para o usuário no component.`. Não sei se são as melhores palavras, mas serve como um start

2017-09-11 12:15 UTC, aureliosaraiva commented
17 words might be misspelled, please check them: compenent, conveção, coresponde, disponiveis, disponivel, ESLint, fillIn, filterByCity, handleFilterEntry, ímoveis, init, keyEvent, keyup, keyUp, QUnit, testámos, toc

2017-09-11 12:20 UTC, aureliosaraiva commented
Teste

2017-09-14 12:31 UTC, aureliosaraiva commented
18 words might be misspelled, please check them: compenent, compoente, conveção, coresponde, disponiveis, disponivel, ESLint, exeutando, fillIn, filterByCity, handleFilterEntry, ímoveis, init, keyEvent, keyup, keyUp, QUnit, testámos

2017-09-18 12:57 UTC, aureliosaraiva commented
19 words might be misspelled, please check them: compenent, compoente, conveção, coresponde, disponiveis, disponivel, ESLint, exeutando, fillIn, filterByCity, handleFilterEntry, ímoveis, init, keyEvent, keyup, keyUp, prenche, QUnit, testámos

2017-09-18 13:42 UTC, aureliosaraiva commented
19 words might be misspelled, please check them: compenent, compoente, conveção, coresponde, disponiveis, disponivel, ESLint, exeutando, fillIn, filterByCity, handleFilterEntry, ímoveis, init, keyEvent, keyup, keyUp, prenche, QUnit, testámos

2017-09-18 14:02 UTC, aureliosaraiva commented
No spelling errors, congratulations!

2017-09-19 12:23 UTC, aureliosaraiva commented
1 words might be misspelled, please check them: metodo

2017-09-19 12:25 UTC, aureliosaraiva commented
No spelling errors, congratulations!

2017-09-19 12:38 UTC, danilovaz commented
@aureliosaraiva Estou revisando :)

2017-09-19 13:01 UTC, danilovaz requested changes
Achei algumas coisinhas para arrumar e algumas sugestões

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Quando nossos usuários estão procurando um imóvel, eles precisam filtrar a pesquisa por uma cidade especifica, por exemplo.
`especifica` p/ `específica`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Chamaremos esse component de `list-filter`, já que tudo o que precisamos é que ele filtre os imóveis disponível.
`os imóveis disponível` p/ `os imóveis disponíveis`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +* um arquivo JavaScript (`app/templates/components/list-filter.hbs`),
(`app/templates/components/list-filter.hbs`) p/ (`app/templates/components/list-filter.js`)

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Esse é um exemplo de [**block form**](../../components/wrapping-content-in-a-component), que permite que o template Handlebars seja renderizado _inside_, dentro do component `list-filter` na expressã
@aureliosaraiva Acho que dá para remover o _inside_  e só deixar o _dentro_

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Observer que nosso template agora possui um novo tipo de helper [`{{input}}`](../../templates/input-helpers), ele funciona como um campo de texto, no qual nosso usuário poderá digitar uma cidade e fi
`Observer` p/ `Observe`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +No exemplo acima, usamos o método hook `init` para criar nossas lista de imóveis iniciais chamando a função `filter` com um valor vazio.
`para criar nossas lista` p/ `para criar nossa lista`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Isso ocorre porque nossa função que faz a filtragem é _synchronous_, o que significa que o código na função é agendado para mais tarde, enquanto o código que chama a função continua a ser executado.
@aureliosaraiva Escreveu _synchronous_ mas na verdade é _asynchronous_

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +A action `filterByCity` no controller `rental` acima, adicionamos uma nova propriedade chamada` query` aos resultados do filtro em vez de apenas retornar um array de imóveis como antes.
`A action` p/ `Na action`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Portanto, verificamos se os resultados correspondem ao valor do filtro, garantindo que os resultados permanecerão em sincronia com a última coisa que o usuário digitou.
@aureliosaraiva O que acha de mudar `coisa` para `informação`?

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Agora você pode avançar para [próxima página](../service/) ou continuar nesta página e fazer os teste de integração e aceitação.
`os teste` p/ `os testes`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Nós adicionaremos algumas funcionalidades adicionais à nossa action `filterByCity` para retornar um único imóvel, representado pela variável `FILTERED_ITEMS` quando qualquer valor estiver definido.
`Nós adicionaremos algumas funcionalidades adicionais` p/ `Nós incluiremos algumas funcionalidades adicionais`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Agora, ambos os cenários de teste de integração devem está passando.
`devem está passando` p/ `devem estar passando`

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Apresentamos dois novos helper neste teste, `fillIn` e` keyEvent`.
Tem um espaço a mais no`keyEvent` aqui: e` keyEvent`.

2017-09-19 13:01 UTC, danilovaz commented on source/guides/tutorial/autocomplete-component.md
> +Uma vez que nossos dados estão codificados em Mirage, sabemos que existe apenas um imóvel na cidade de "Seattle", por isso afirmamos que o número de imóvel é um e que a localização exibida é chamada
`o número de imóvel é um` p/ `o número de imóvel é 1`

2026-03-29 14:38 UTC, closed without merging