Tradução ember-inspector
ember-brasil/website pull request #64
Opened 2017-09-11 23:50 UTC by bfmjr

2017-09-12 01:02 UTC, aureliosaraiva commented
Alguns erros ortografico detectados pelo travis: Daya, didicado, icone, inpecionar, inspecional, inspensonar, intancias, mantem, persistencia,tambem

@bfmjr o travis deveria criar um comentário automaticamente com essas palavras, estranho ele não fazer isso :confused:

2017-09-12 01:08 UTC, aureliosaraiva commented on source/guides/ember-inspector/container.md
> +Cada aplicação Ember tem um container que mantem as intancias de objetos para você. Você pode inpecionar essas instancias usando a Container tab. Isso é útil para objetos que não estão no menu didica
usando a tab chamada `Container`

2017-09-12 01:09 UTC, aureliosaraiva commented on source/guides/ember-inspector/container.md
> +Cada aplicação Ember tem um container que mantem as intancias de objetos para você. Você pode inpecionar essas instancias usando a Container tab. Isso é útil para objetos que não estão no menu didica
serviços -> services

2017-09-12 01:11 UTC, aureliosaraiva commented on source/guides/ember-inspector/data.md
>  You can inspect your models by clicking on the `Data` tab. Check out [Building a Data Custom Adapter][building-data-adapter] below if you maintain your own persistence library.
Acho que ficou sem tradução.

2017-09-12 01:12 UTC, aureliosaraiva commented on source/guides/ember-inspector/data.md
>  You can inspect your models by clicking on the `Data` tab. Check out [Building a Data Custom Adapter][building-data-adapter] below if you maintain your own persistence library.
Acho que ficou sem tradução aqui.

2017-09-12 01:15 UTC, bfmjr commented on source/guides/ember-inspector/data.md
>  You can inspect your models by clicking on the `Data` tab. Check out [Building a Data Custom Adapter][building-data-adapter] below if you maintain your own persistence library.
Essa página inda estou iniciando a tradução.

2017-09-12 01:17 UTC, aureliosaraiva requested changes
A tradução está ok, acho que precisa de alguns ajustes. Também vi que ainda tem texto em inglês, é legal remover ele também.

Onde está `Inspector` pode deixar como `Ember Inspector` sem tradução e adicionando o Ember na frente, acho que fica melhor.

2017-11-28 11:17 UTC, aureliosaraiva commented
@bfmjr e ai, como está? Rola resolver o problema no CI?

2021-10-15 00:50 UTC, closed without merging